/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "necxcwhuzylsumlkkmlk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lY3hjd2h1enlsc3VtbGtrbWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1ODUxMDAsImV4cCI6MjA4MzE2MTEwMH0.UR8t4B8kLpWl5USe-Jamd3rJDPNuR1-tvmzSVwcqB5A"